import Head from 'next/head'
import Layout from '../components/Layout'
import ServiceArea from '../components/ServiceArea'
import "swiper/css/bundle";

export default function Home() {
  return (
    <Layout >
      <div className="bg-black min-h-screen" >
        <Head>
          <title>Food ordering app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="container mx-auto p-4">
          <h1 className="text-4xl font-bold text-center text-white">
            Welcome to the Food Ordering App
          </h1>
          <p className="mt-6 max-w-2xl mx-auto text-lg text-center text-gray-300">
            Craving something delicious? You're in the right place! Discover a world of mouthwatering burgers, pizzas, fresh salads, and decadent desserts—all at your fingertips.
          </p>
        </main>
        
        <ServiceArea />
      </div>
    </Layout>
  )
}
 